export const todoContainer: string;
export const todoText: string;
export const todoTextContainer: string;
export const todoDone: string;
export const todoClose: string;
export const todoInput: string;
export const completedCheck: string;
export const notCompletedCheck: string;
export const completedText: string;
